1810 fix
InstituteforDiseaseModeling/idmtools pull request #1825
Opened 2022-08-25 19:47 UTC by emilykclaps

Addresses core issues of #1810 
This PR incorporates id-generation plugins for item ID's. The name of the plugin the user desires to use can be specified in the .ini file under [COMMON] > 'id_generator'. The 2 plugins we defined are:
- uuid: returns a uuid as the item id (default option)
- item_sequence: returns a sequential id for the respective item based on the most recently created/used id for that respective item type. A sequence file is created that keeps track of these sequential ids for each item type (experiment, simulation, etc) and returns and stores the next id. The user can customize both the sequence file name as well as the id string format using the 'sequence_file' and 'id_format_str' options under an [item_sequence] section in the .ini file. See added docs for more detail and an example.

Documentation and tests were also added for this feature.

*Note - the id sequential generator plugin is intended to be used with Slurm, not with COMPS.

To support this, we also added tickets related
#1930
#1936
#1937
#1938
#1939
#1954

2022-11-07 21:01 UTC, shchen-idmod commented
(idmtools_dev_39) C:\Users\sharonch\github_dev\idmtools>idmtools --help
```
You are using a development version of idmtools, version 1.7.1+nightly!
Traceback (most recent call last):
  File "c:\venv\idmtools_dev_39\Scripts\idmtools-script.py", line 33, in <module>
    sys.exit(load_entry_point('idmtools-cli', 'console_scripts', 'idmtools')())
  File "c:\users\sharonch\github_dev\idmtools\idmtools_cli\idmtools_cli\main.py", line 17, in main
    from idmtools_cli.cli.entrypoint import cli
  File "c:\users\sharonch\github_dev\idmtools\idmtools_cli\idmtools_cli\cli\entrypoint.py", line 3, in <module>
    from idmtools import IdmConfigParser
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\__init__.py", line 16, in <module>
    IdmConfigParser.ensure_init()
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\config\idm_config_parser.py", line 359, in ensure_init
    cls(dir_path, file_name)
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\config\idm_config_parser.py", line 75, in __new__
    FunctionPluginManager.instance().hook.idmtools_on_start()
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\utils\decorators.py", line 88, in instance
    cls.__singleton_instance = cls()
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\registry\functions.py", line 26, in __init__
    self.load_setuptools_entrypoints(hookspecs.IDMTOOLS_HOOKS.lower())
  File "c:\venv\idmtools_dev_39\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\sharonch\github_dev\idmtools\idmtools_core\idmtools\plugins\item_sequence.py", line 96, in <module>
    def idmtools_generate_id(item: IEntity) -> str:
NameError: name 'IEntity' is not defined
```

2022-11-10 21:46 UTC, shchen-idmod commented
run examples/python_model/python_sim.py:

```
C:\venv\idmtools_devbranch_39\Scripts\python.exe C:/Users/sharonch/git_dev/idmtools/examples/python_model/python_sim.py
You are using a development version of idmtools, version 1.7.1+nightly!
INI File Used: C:\Users\sharonch\git_dev\idmtools\examples\idmtools.ini

[BELEGOST]
{
   "type": "COMPS",
   "endpoint": "https://comps.idmod.org",
   "environment": "BELEGOST"
}
Traceback (most recent call last):
  File "C:\Users\sharonch\git_dev\idmtools\examples\python_model\python_sim.py", line 123, in <module>
    with Platform('BELEGOST'):
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\platform_factory.py", line 88, in __new__
    platform = cls._create_from_block(block, missing_ok=missing_ok, **kwargs)
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\platform_factory.py", line 225, in _create_from_block
    return platform_cls(**inputs)
  File "<string>", line 23, in __init__
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_platform_comps\idmtools_platform_comps\comps_platform.py", line 114, in __post_init__
    super().__post_init__()
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\entities\iplatform.py", line 145, in __post_init__
    PlatformPersistService.save(self)
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\services\ipersistance_service.py", line 84, in save
    cache.set(obj.uid, obj, retry=True)
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\interfaces\iitem.py", line 69, in uid
    raise RuntimeError(f"Could not find the id plugin idmtools_id_generate_{id_gen} defined by id_generator in your idmtools.ini."
RuntimeError: Could not find the id plugin idmtools_id_generate_uuid defined by id_generator in your idmtools.ini.Please use one of the following plugins:
```

2022-11-10 22:47 UTC, devclinton commented
> run examples/python_model/python_sim.py:
> 
> ```
> C:\venv\idmtools_devbranch_39\Scripts\python.exe C:/Users/sharonch/git_dev/idmtools/examples/python_model/python_sim.py
> You are using a development version of idmtools, version 1.7.1+nightly!
> INI File Used: C:\Users\sharonch\git_dev\idmtools\examples\idmtools.ini
> 
> [BELEGOST]
> {
>    "type": "COMPS",
>    "endpoint": "https://comps.idmod.org",
>    "environment": "BELEGOST"
> }
> Traceback (most recent call last):
>   File "C:\Users\sharonch\git_dev\idmtools\examples\python_model\python_sim.py", line 123, in <module>
>     with Platform('BELEGOST'):
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\platform_factory.py", line 88, in __new__
>     platform = cls._create_from_block(block, missing_ok=missing_ok, **kwargs)
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\platform_factory.py", line 225, in _create_from_block
>     return platform_cls(**inputs)
>   File "<string>", line 23, in __init__
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_platform_comps\idmtools_platform_comps\comps_platform.py", line 114, in __post_init__
>     super().__post_init__()
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\entities\iplatform.py", line 145, in __post_init__
>     PlatformPersistService.save(self)
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\services\ipersistance_service.py", line 84, in save
>     cache.set(obj.uid, obj, retry=True)
>   File "C:\Users\sharonch\git_dev\idmtools\idmtools_core\idmtools\core\interfaces\iitem.py", line 69, in uid
>     raise RuntimeError(f"Could not find the id plugin idmtools_id_generate_{id_gen} defined by id_generator in your idmtools.ini."
> RuntimeError: Could not find the id plugin idmtools_id_generate_uuid defined by id_generator in your idmtools.ini.Please use one of the following plugins:
> ```

Did you re-run setup? Any changes to setup.py always require re-running setup

2022-11-10 22:52 UTC, shchen-idmod commented
> Did you re-run setup? Any changes to setup.py always require re-running setup
I did not. now after rerun bootstrap.py it is OK.

2022-11-11 00:41 UTC, emilykclaps commented
@shchen-idmod @devclinton just pushed last couple changes; I think you're good to review now. Let me know if you spot anything else that needs updating. Also @devclinton feel free to respond to the portions of Zhaowei's feedback that are not of concern that we had discussed.

2022-11-11 07:45 UTC, shchen-idmod requested changes

2022-11-11 07:45 UTC, shchen-idmod commented on idmtools_core/tests/test_item_sequence.py
> +    @pytest.mark.performance
Can you define performance in pytest.ini file. Otherwise this mark is not applyed

2022-11-11 07:48 UTC, shchen-idmod commented
There is error for platform("Test") in windows:
```
2022-11-10 23:46:27,213.213 C:\Users\sharonch\git_dev\idmtools\idmtools_test\idmtools_test\utils\execute_operations\simulate_operations.py:89 run_simulation [ERROR] (34000,30984) - [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\sharonch\git_dev\idmtools\idmtools_test\idmtools_test\utils\execute_operations\simulate_operations.py", line 72, in run_simulation
    p = subprocess.Popen(
  File "c:\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
You can repro by running tests_sequence.py--test_id case then look at idmtools.log

2022-11-11 07:51 UTC, shchen-idmod requested changes

2022-11-11 07:51 UTC, shchen-idmod commented on idmtools_core/tests/test_performance.py
> +    def test_id_generation(self):
Can we mark this case "skip" or "performance" then skip performance case with test-all? It take very too long time and no validation. so not good for automation suite

2022-11-11 07:53 UTC, shchen-idmod requested changes

2022-11-11 07:53 UTC, shchen-idmod commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertTrue(run_time_a <= run_time_b or (run_time_a - run_time_b) > (run_time_b * .10))
This is not always true. Maybe we should skip with performance test

2022-11-11 07:54 UTC, shchen-idmod requested changes

2022-11-11 07:54 UTC, shchen-idmod commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertTrue(run_time_a <= run_time_b or (run_time_a - run_time_b) > (run_time_b * .10))
This is not always true

2022-11-11 08:00 UTC, shchen-idmod commented
For some reason, I can not get successful result by running pymake test-all for core test in Windows
Always get this error: (even just one test_xxx.py)
```
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\venv\zdu_idmtools_39\Scripts\py.test.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "c:\venv\zdu_idmtools_39\lib\site-packages\_pytest\config\__init__.py", line 190, in console_main
    code = main()
  File "c:\venv\zdu_idmtools_39\lib\site-packages\_pytest\config\__init__.py", line 167, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\_pytest\main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\_pytest\main.py", line 305, in wrap_session
    config.hook.pytest_sessionfinish(
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\_pytest\terminal.py", line 808, in pytest_sessionfinish
    outcome.get_result()
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pytest_html\html_report.py", line 333, in pytest_sessionfinish
    self._save_report(report_content)
  File "c:\venv\zdu_idmtools_39\lib\site-packages\pytest_html\html_report.py", line 259, in _save_report
    self.logfile.write_text(report_content)
  File "c:\python39\lib\pathlib.py", line 1276, in write_text
    return f.write(data)
  File "c:\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 30423-30432: character maps to <undefined>
make[1]: *** [test-all] Error 1
make[1]: Leaving directory `C:/Users/sharonch/git_zdu/idmtools/idmtools_core/tests'
```
If I remove --html=reports/core.test_results.html then I can get all test result finish run.

2022-11-11 18:04 UTC, shchen-idmod commented
This must be unrelated to this PR with python 3.7.8
```
test_analyze_manager.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\idmtools\core\platform_factory.py:88: in __new__
    platform = cls._create_from_block(block, missing_ok=missing_ok, **kwargs)
..\idmtools\core\platform_factory.py:225: in _create_from_block
    return platform_cls(**inputs)
<string>:10: in __init__
    ???
..\..\idmtools_test\idmtools_test\utils\test_platform.py:44: in __post_init__
    super().__post_init__()
..\idmtools\entities\iplatform.py:145: in __post_init__
    PlatformPersistService.save(self)
..\idmtools\services\ipersistance_service.py:84: in save
    cache.set(obj.uid, obj, retry=True)
C:\venv\idmtools_emily_37\lib\site-packages\diskcache\fanout.py:120: in set
    index = self._hash(key) % self._count
C:\venv\idmtools_emily_37\lib\site-packages\diskcache\core.py:126: in hash
    disk_key, _ = self.put(key)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <diskcache.core.Disk object at 0x0000023FCEBB2808>
key = UUID('7d74153d-7ecc-457e-a4e2-18fe0fd4f38f')

    def put(self, key):
        """Convert `key` to fields key and raw for Cache table.
    
        :param key: key to convert
        :return: (database key, raw boolean) pair
    
        """
        # pylint: disable=unidiomatic-typecheck
        type_key = type(key)
    
        if type_key is bytes:
            return sqlite3.Binary(key), True
        elif (
            (type_key is str)
            or (
                type_key is int
                and -9223372036854775808 <= key <= 9223372036854775807
            )
            or (type_key is float)
        ):
            return key, True
        else:
>           data = pickle.dumps(key, protocol=self.pickle_protocol)
E           ValueError: pickle protocol must be <= 4

C:\venv\idmtools_emily_37\lib\site-packages\diskcache\core.py:161: ValueError
```

2022-11-11 23:43 UTC, shchen-idmod commented
Got this error for existing suite in slurm. (Suite00000 was from previous run)
suite = platform.get_item(item_id="Suite000000", item_type=ItemType.SUITE)
```

pydev debugger: warning: trying to add breakpoint to file that does not exist: /home/schen/git_emily/idmtools/examples/python_model/run_example.py (will have no effect)
You are using a development version of idmtools, version 1.7.1+nightly!
INI File Used: /home/schen/git_emily/idmtools/examples/native_slurm/idmtools.ini

[SLURM_TEST]
{
   "type": "Slurm",
   "mode": "LOCAL"
}
Traceback (most recent call last):
  File "/home/schen/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/schen/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/schen/git_emily/idmtools/examples/native_slurm/python_sims1.py", line 26, in <module>
    suite = platform.get_item(item_id="Suite000000", item_type=ItemType.SUITE)
  File "/home/schen/git_emily/idmtools/idmtools_core/idmtools/entities/iplatform.py", line 234, in get_item
    return_object = self._convert_platform_item_to_entity(ce, **kwargs)
  File "/home/schen/git_emily/idmtools/idmtools_core/idmtools/entities/iplatform.py", line 527, in _convert_platform_item_to_entity
    return getattr(self, interface).to_entity(platform_item, **kwargs)
  File "/home/schen/git_emily/idmtools/idmtools_platform_slurm/idmtools_platform_slurm/platform_operations/suite_operations.py", line 115, in to_entity
    suite.uid = UUID(slurm_suite.uid)
  File "/usr/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
python-BaseException
```

2022-11-11 23:51 UTC, shchen-idmod commented
[python_sims1.py.txt](https://github.com/InstituteforDiseaseModeling/idmtools/files/9993685/python_sims1.py.txt)
```
ssh://schen@10.24.46.241:22/home/schen/venv/idmtools_emily_38/bin/python -u /home/schen/git_emily/idmtools/examples/native_slurm/python_sims1.py
You are using a development version of idmtools, version 1.7.1+nightly!
INI File Used: /home/schen/git_emily/idmtools/examples/native_slurm/idmtools.ini

[SLURM_TEST]
{
   "type": "Slurm",
   "mode": "LOCAL"
}
Traceback (most recent call last):
  File "/home/schen/git_emily/idmtools/examples/native_slurm/python_sims1.py", line 46, in <module>
    am = AnalyzeManager(configuration={}, platform=platform,
  File "/home/schen/git_emily/idmtools/idmtools_core/idmtools/analysis/analyze_manager.py", line 149, in __init__
    item.uid = item.id if isinstance(item.id, UUID) else UUID(item.id)
  File "/usr/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecima
```l UUID string

2022-11-11 23:59 UTC, shchen-idmod commented
If you use sequence id to test_suite_experiment.py in idmtools_platform_slurm/tests, most of test failed.
Discovering experiment assets from tasks: 100%|██████████| 1/1 [00:00<00:00, 2458.56simulation/s]
Commissioning Simulations: 100%|██████████| 1/1 [00:00<00:00, 39.51simulation/s]

```
test_suite_experiment.py:132 (TestSuiteExperiment.test_5)
self = <tests.test_suite_experiment.TestSuiteExperiment testMethod=test_5>

    def test_5(self):
        experiment = Experiment.from_task(self.task, name="run_task")
        suite = Suite(name='Idm Suite')
        experiment.suite = suite
        suite.run(platform=self.platform, wait_until_done=False, wait_on_done=False, dry_run=True)
>       self.verify_result(suite)

test_suite_experiment.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_suite_experiment.py:50: in verify_result
    experiments = self.platform.get_children(suite.id, item_type=ItemType.SUITE)
../../idmtools_core/idmtools/entities/iplatform.py:325: in get_children
    ce = item or self.get_item(item_id, raw=raw, item_type=item_type)
../../idmtools_core/idmtools/entities/iplatform.py:234: in get_item
    return_object = self._convert_platform_item_to_entity(ce, **kwargs)
../../idmtools_core/idmtools/entities/iplatform.py:527: in _convert_platform_item_to_entity
    return getattr(self, interface).to_entity(platform_item, **kwargs)
../idmtools_platform_slurm/platform_operations/suite_operations.py:115: in to_entity
    suite.uid = UUID(slurm_suite.uid)
```

2022-12-02 04:26 UTC, shchen-idmod commented
I have absolutely fresh experimement/simulations. But my simulation id start from Simulation-000030

![image](https://user-images.githubusercontent.com/38014764/205214640-7ae59e24-f5ed-4184-9abf-1dc1be49a462.png)

2022-12-02 22:05 UTC, shchen-idmod requested changes

2022-12-02 22:05 UTC, shchen-idmod commented on idmtools_platform_slurm/idmtools_platform_slurm/slurm_operations/local_operations.py
> +            raise RuntimeError('Item directory already exists. Exist_ok flag set to false to avoid data being overwritten.')
Maybe better to give more specific about which target directory already exists.

2022-12-03 23:47 UTC, shchen-idmod commented
In native_slurm python_sims.py example, add these 2 lines before suite.run
```
for sim in experiment.simulations:
    print(sim.id)
```

suite.run(platform=platform, wait_until_done=True, max_running_jobs=10, retries=5, dry_run=False)
the simulation ids will be increased another 15
![image](https://user-images.githubusercontent.com/38014764/205467087-cea0fd2e-7ba8-424b-8c72-90b1320c72fe.png)

2022-12-05 18:31 UTC, emilykclaps commented
> In native_slurm python_sims.py example, add these 2 lines before suite.run
> 
> ```
> for sim in experiment.simulations:
>     print(sim.id)
> ```
> 
> suite.run(platform=platform, wait_until_done=True, max_running_jobs=10, retries=5, dry_run=False) the simulation ids will be increased another 15 ![image](https://user-images.githubusercontent.com/38014764/205467087-cea0fd2e-7ba8-424b-8c72-90b1320c72fe.png)

I believe this is actually expected behavior that Clinton and I had looked at based on a previous comment. Calling print on each simulation generates an ID for each prematurely. I'm still trying to figure out what is causing the sims to start at twice the # of simulations, though.

2022-12-06 01:40 UTC, shchen-idmod commented
> > In native_slurm python_sims.py example, add these 2 lines before suite.run
> > ```
> > for sim in experiment.simulations:
> >     print(sim.id)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > suite.run(platform=platform, wait_until_done=True, max_running_jobs=10, retries=5, dry_run=False) the simulation ids will be increased another 15 ![image](https://user-images.githubusercontent.com/38014764/205467087-cea0fd2e-7ba8-424b-8c72-90b1320c72fe.png)
> 
> I believe this is actually expected behavior that Clinton and I had looked at based on a previous comment. Calling print on each simulation generates an ID for each prematurely. I'm still trying to figure out what is causing the sims to start at twice the # of simulations, though.

I don't understand why this is expected behavior. user may call sim.id before run experiment for debug. but this will make overall sim id increased without good explanation to user.

2022-12-12 18:51 UTC, shchen-idmod requested changes

2022-12-12 18:51 UTC, shchen-idmod commented on idmtools_core/idmtools/entities/experiment.py
> +        result = result
no need to do result=result

2022-12-15 18:54 UTC, shchen-idmod requested changes

2022-12-15 18:54 UTC, shchen-idmod commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertEqual(sequence_file_json, backup_file_json)
This test failed. sequence file and sequence backup file do not match.

2022-12-15 19:18 UTC, emilykclaps commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertEqual(sequence_file_json, backup_file_json)
@shchen-idmod do you have the latest checkins? The test passes for me; the .ini for this specific test is using the default location to write the item_sequences file (which for you should be something like 'C:\Users\sharonch\.idmtools\itemsequence')

2022-12-15 19:24 UTC, shchen-idmod commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertEqual(sequence_file_json, backup_file_json)
I do have the latest checkins. you may still have previous bak file. if you delete all files under ~/.idmtools/itemsequence/*, then rerun the test, you will see .bak file is missing.

2022-12-15 20:10 UTC, emilykclaps commented on idmtools_core/tests/test_item_sequence.py
> +        self.assertEqual(sequence_file_json, backup_file_json)
Ah, thank you for the catch. This was happening because I had added a post_run hook in the test execute experiment operations (to address the previous issue) but forgot to include the logic to make the backup file there as well. Should be fixed now.

2022-12-15 22:14 UTC, shchen-idmod requested changes

2022-12-15 22:14 UTC, shchen-idmod commented on idmtools_test/idmtools_test/utils/execute_operations/experiment_operations.py
> +        if IdmConfigParser.get_option(None, "id_generator", "uuid").lower() == "item_sequence":
This is the exactly what super class function of post_run_item does. so no need to copy code. just need call super function.

2022-12-15 22:27 UTC, shchen-idmod commented
https://github.com/InstituteforDiseaseModeling/idmtools/blob/e3ec545498e2b1f35c8a5896bd94fdd496ffdd47/idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py#L44
https://github.com/InstituteforDiseaseModeling/idmtools/blob/e3ec545498e2b1f35c8a5896bd94fdd496ffdd47/idmtools_platform_comps/idmtools_platform_comps/comps_operations/simulation_operations.py#L114
https://github.com/InstituteforDiseaseModeling/idmtools/blob/e3ec545498e2b1f35c8a5896bd94fdd496ffdd47/idmtools_platform_comps/idmtools_platform_comps/comps_operations/suite_operations.py#L29
https://github.com/InstituteforDiseaseModeling/idmtools/blob/e3ec545498e2b1f35c8a5896bd94fdd496ffdd47/idmtools_platform_comps/idmtools_platform_comps/comps_operations/workflow_item_operations.py#L35
https://github.com/InstituteforDiseaseModeling/idmtools/blob/e3ec545498e2b1f35c8a5896bd94fdd496ffdd47/idmtools_platform_comps/idmtools_platform_comps/comps_operations/asset_collection_operations.py#L35
You still have lot of places using UUID for id as above lines. Do you intend to do that?

2022-12-16 18:30 UTC, ZDu-IDM requested changes

2022-12-16 18:30 UTC, ZDu-IDM commented on idmtools_test/idmtools_test/utils/execute_operations/experiment_operations.py
> +        super().post_run_item(experiment)
We need to pass **kwargs to the call:

`super().post_run_item(experiment)`

2023-01-10 19:14 UTC, shchen-idmod approved these changes
Tested the latest fixes. Even there are still few issues(like can not random print id, too fridge if let user define sequence file), but overall feature is good.

2023-01-10 21:08 UTC, ZDu-IDM approved these changes

2023-02-06 20:19 UTC, shchen-idmod commented
Can we fix conflicts?

2023-02-09 22:58 UTC, emilykclaps commented
@shchen-idmod just resolved conflicts. Where are we with this PR? Can we merge to dev, or did you want to release to separate branch until ready to merge? Thx!

2023-02-10 00:02 UTC, shchen-idmod commented
FAILED test_slurm_cancel1.py::TestSlurmCanceling::test_canceling_a_full_experiment - NameError: name 'meta' is not defined
FAILED test_slurm_cancel1.py::TestSlurmCanceling::test_canceling_a_full_suite - NameError: name 'meta' is not defined
FAILED test_slurm_cancel1.py::TestSlurmCanceling::test_canceling_a_single_simulation - NameError: name 'meta' is not defined
You may missing something from latest code.

2023-02-21 23:26 UTC, shchen-idmod commented
There is known issue about build-docs. Other than that everything looks good

2023-02-21 23:26 UTC, merged