Changes needed to support Calibra ticket (regarding SiteDataPlotter)
InstituteforDiseaseModeling/idmtools pull request #1940
Opened 2022-11-07 20:25 UTC by ZDu-IDM

This PR addressed the following

Add utility tools to convert Windows file path to Linux file path for Slurm #1659
https://github.com/InstituteforDiseaseModeling/idmtools/issues/1659

SiteDataPlotter needs to be refactored to support SlurmPlatform #157
https://github.com/InstituteforDiseaseModeling/idmtools-calibra/issues/157

**Note**: this PR did all the required idmtools change for above calibra ticket.

2022-11-08 18:48 UTC, devclinton approved these changes

2022-11-08 18:49 UTC, devclinton commented
@ZDu-IDM - Can you fix the linting issues?

2022-11-08 20:06 UTC, ZDu-IDM commented
> @ZDu-IDM - Can you fix the linting issues?

Got all linting issues fixed, thanks!

2022-11-09 17:46 UTC, shchen-idmod commented
This PR failed lot of tests: https://github.com/shchen-idmod/idmtools-1/actions/runs/3425970433/jobs/5707286888 with same reason. I suspect, we may change environment variable in host somehow with this PR.

2022-11-09 19:30 UTC, shchen-idmod commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +            Dict
Can Dict comment more specific?

2022-11-09 19:31 UTC, ZDu-IDM commented
> This PR failed lot of tests: https://github.com/shchen-idmod/idmtools-1/actions/runs/3425970433/jobs/5707286888 with same reason. I suspect, we may change environment variable in host somehow with this PR. Updated, tests are running on this branch as base and new test I added: [ZDu-IDM#1](https://github.com/ZDu-IDM/zdu_idmtools/pull/1). Failed tests seem appear after running my new testcases: test_create_sim_directory_map.py

[FIXED] make set/clear a pair usage, please verify, thanks!

2022-11-09 20:00 UTC, shchen-idmod requested changes

2022-11-09 20:00 UTC, shchen-idmod commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        clear_linux_mounts(self.platform)
This line need after result dict.

2022-11-09 20:13 UTC, ZDu-IDM commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        clear_linux_mounts(self.platform)
[Fixed] Good catch, thanks!

2022-11-10 21:15 UTC, shchen-idmod approved these changes
All tests passed. approved~

2022-11-10 21:26 UTC, merged