File platform: implemented workflow (folders and files are generated).
InstituteforDiseaseModeling/idmtools pull request #2019
Opened 2023-02-16 17:21 UTC by ZDu-IDM

Implemented FilePlatform workflow:
- user can run Suite/Experiment (like SlurmPlatform)
- Suite/Experiment/Simulation folder structure with full files got created/generated
- All functions, like get_item, get_files, etc. should work
- Only left work is run experiment (execute batch files)

**Note**: batch files execution will be implemented in next PR

2023-02-16 17:25 UTC, devclinton approved these changes

2023-02-22 18:13 UTC, shchen-idmod commented
Can we add bootstrap install for idmtools_platform_file package?

2023-02-22 18:14 UTC, shchen-idmod requested changes

2023-02-22 18:14 UTC, shchen-idmod commented on idmtools_platform_file/setup.py
> +    version='1.7.5'
Please update to 1.7.5+nightly

2023-02-22 18:15 UTC, shchen-idmod requested changes

2023-02-22 18:15 UTC, shchen-idmod commented on idmtools_platform_file/.bumpversion.cfg
> +current_version = 1.7.4
1.7.5+nightly

2023-02-22 18:15 UTC, shchen-idmod requested changes

2023-02-22 18:15 UTC, shchen-idmod commented on idmtools_platform_file/idmtools_platform_file/__init__.py
> +__version__ = "1.7.5"
1.7.5+nightly

2023-02-22 18:53 UTC, ZDu-IDM commented on idmtools_platform_file/setup.py
> +    version='1.7.5'
Version updated, thanks.

2023-02-22 18:53 UTC, ZDu-IDM commented on idmtools_platform_file/.bumpversion.cfg
> +current_version = 1.7.4
Version updated, thanks.

2023-02-22 18:53 UTC, ZDu-IDM commented on idmtools_platform_file/idmtools_platform_file/__init__.py
> +__version__ = "1.7.5"
Version updated, thanks.

2023-02-22 18:54 UTC, ZDu-IDM commented
> Can we add bootstrap install for idmtools_platform_file package?

Done, thanks.

2023-02-22 20:21 UTC, shchen-idmod commented
Can you fix lint?

2023-02-22 21:41 UTC, ZDu-IDM commented
> Can you fix lint?

Fixed several lint errors, the rest will be fixed in next PR. Thanks!

2023-02-23 17:46 UTC, shchen-idmod approved these changes
Looks good now

2023-02-27 19:34 UTC, merged