File platform: implemented experiment execution (batch and status, etc.)
InstituteforDiseaseModeling/idmtools pull request #2025
Opened 2023-02-27 17:25 UTC by ZDu-IDM

This PR implemented:
- generated batch files: batch.sh, run_simulation.sh and _run.sh
- support singularity
- support two ways to run simulations:
   - sequence
   - parallel
- simulation status (similar to Slurm Platform)

**Extras work**
- implement CLI utility to check running status
- to be done in next PR

2023-02-27 19:35 UTC, devclinton requested changes
The file platform should not actually execute anything. Otherwise, everything looks good

2023-02-27 19:35 UTC, devclinton commented on idmtools_platform_file/idmtools_platform_file/file_platform.py
> +            result = subprocess.run(['bash', 'batch.sh'], stdout=subprocess.PIPE,
We do not want to execute the file. The file platform _produces_ files but does not execute.

2023-02-28 23:25 UTC, ZDu-IDM commented on idmtools_platform_file/idmtools_platform_file/file_platform.py
> +            result = subprocess.run(['bash', 'batch.sh'], stdout=subprocess.PIPE,
@devclinton , fixed (removed execution code totally), please verify, thanks!

2023-03-01 19:41 UTC, shchen-idmod approved these changes
Looks good

2023-03-09 19:08 UTC, shchen-idmod approved these changes
Tested again

2023-03-09 20:41 UTC, devclinton approved these changes

2023-03-09 20:43 UTC, merged