First PR to fix some bugs
InstituteforDiseaseModeling/idmtools pull request #2149
Opened 2023-11-30 16:42 UTC by ZDu-IDM

Fixed
#1657
#1925
#2138
#2137
#2135
#2136
#2140

2023-12-04 17:37 UTC, shchen-idmod requested changes

2023-12-04 17:37 UTC, shchen-idmod commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        super().post_creation(self.platform, **kwargs)
there is no post_creation in super class.

2023-12-04 17:40 UTC, shchen-idmod commented on idmtools_core/idmtools/analysis/platform_anaylsis.py
> +            simulaiton_ids: Simulation ids
typo: simulaiton_ids, should be simulation_ids

2023-12-04 17:45 UTC, ZDu-IDM commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        super().post_creation(self.platform, **kwargs)
Fixed, good catch!

2023-12-04 17:45 UTC, ZDu-IDM commented on idmtools_core/idmtools/analysis/platform_anaylsis.py
> +            simulaiton_ids: Simulation ids
Fixed, good catch!

2023-12-04 23:55 UTC, shchen-idmod commented
This new test failed: You can add to comps test file to the end: test_python_experiment.py

 ```
def test_experiment_hooks(self):
        base_task = CommandTask(command="python --version")
        sim = Simulation(task=base_task)

        exp = Experiment(name='ExpHooks')
        exp.simulations = [sim]

        def add_pre_exp_tag(item: Experiment, platform: 'COMPSPlatform'):
            item.tags['pre_tag'] = "pre"

        def update_post_exp_tags(item: Experiment, platform: 'COMPSPlatform'):
            tags = {"post_tag": "post"}
            update_item(platform, exp.id, ItemType.EXPERIMENT, tags)

        exp.add_pre_creation_hook(add_pre_exp_tag)
        exp.add_post_creation_hook(update_post_exp_tags)

        exp.run(wait_until_done=True)
        tag_value = "idmtools.entities.command_task.CommandTask"
        exp_tags = {'pre_tag': "pre", 'post_tag': 'post', 'task_type': tag_value}
        self.validate_exp_tags(exp.id, exp_tags)

    def validate_exp_tags(self, exp_id, expected_tags):
        tags = COMPSExperiment.get(exp_id, QueryCriteria().select_children('tags')).tags
        tags.pop('idmtools')
        self.assertDictEqual(tags, expected_tags)
```

2023-12-05 00:13 UTC, shchen-idmod commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        super().post_create(self.platform, **kwargs)
Actually previous line was good: experiment.post_creation(self.platform)

2023-12-05 01:11 UTC, shchen-idmod commented
For log bug https://github.com/InstituteforDiseaseModeling/idmtools/issues/2137
with test:
```
def test_console_off_log_off1(self):
        ini_content = f"""
        [Logging]
            level = CRITICAL
            console = on
            enable_file_logging = off
            user_output = on
        """
        self.create_temp_ini(ini_content)
        IdmConfigParser(file_name=self.tempfile_ini.name)
        self.platform = Platform('SLURMSTAGE')
        logger_demo.write_some_logs(user=True, root=True, comps=True, exp=True)
```
Used to print: 
2023-12-04 17:09:26,172 BMGF-R913QDCE root[57444] CRITICAL root: 5
2023-12-04 17:09:26,173 BMGF-R913QDCE user[57444] CRITICAL user: 55

Now print:
2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] DEBUG root: 1
2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] INFO root: 2
2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] WARNING root: 3
2023-12-04 17:10:06,147 BMGF-R913QDCE root[11904] ERROR root: 4
2023-12-04 17:10:06,147 BMGF-R913QDCE root[11904] CRITICAL root: 5
2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] DEBUG user: 11
2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] INFO user: 22
2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] WARNING user: 33
2023-12-04 17:10:06,148 BMGF-R913QDCE user[11904] ERROR user: 44
2023-12-04 17:10:06,148 BMGF-R913QDCE user[11904] CRITICAL user: 55

Note: I only need CRITICAL

2023-12-05 04:51 UTC, shchen-idmod commented on idmtools_platform_general/idmtools_platform_file/platform_operations/asset_collection_operations.py
> +            self.pre_create(item.assets)
this pre_create and post_create for asset_collection seems never get used with client pre and post hook.

2023-12-05 19:47 UTC, ZDu-IDM commented on idmtools_platform_comps/idmtools_platform_comps/comps_operations/experiment_operations.py
> +        super().post_create(self.platform, **kwargs)
Fixed wrong parameter issue.

2023-12-05 19:48 UTC, ZDu-IDM commented
> For log bug #2137 with test:
> 
> ```
> def test_console_off_log_off1(self):
>         ini_content = f"""
>         [Logging]
>             level = CRITICAL
>             console = on
>             enable_file_logging = off
>             user_output = on
>         """
>         self.create_temp_ini(ini_content)
>         IdmConfigParser(file_name=self.tempfile_ini.name)
>         self.platform = Platform('SLURMSTAGE')
>         logger_demo.write_some_logs(user=True, root=True, comps=True, exp=True)
> ```
> 
> Used to print: 2023-12-04 17:09:26,172 BMGF-R913QDCE root[57444] CRITICAL root: 5 2023-12-04 17:09:26,173 BMGF-R913QDCE user[57444] CRITICAL user: 55
> 
> Now print: 2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] DEBUG root: 1 2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] INFO root: 2 2023-12-04 17:10:06,146 BMGF-R913QDCE root[11904] WARNING root: 3 2023-12-04 17:10:06,147 BMGF-R913QDCE root[11904] ERROR root: 4 2023-12-04 17:10:06,147 BMGF-R913QDCE root[11904] CRITICAL root: 5 2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] DEBUG user: 11 2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] INFO user: 22 2023-12-04 17:10:06,147 BMGF-R913QDCE user[11904] WARNING user: 33 2023-12-04 17:10:06,148 BMGF-R913QDCE user[11904] ERROR user: 44 2023-12-04 17:10:06,148 BMGF-R913QDCE user[11904] CRITICAL user: 55
> 
> Note: I only need CRITICAL

Fixed.

2023-12-06 05:03 UTC, shchen-idmod requested changes

2024-01-08 18:01 UTC, shchen-idmod approved these changes

2024-01-08 18:02 UTC, merged